version: '3.8'

services:
  # ==========================================
  # Aplicação Principal (Backend + Frontend)
  # ==========================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acamp-termo-app
    restart: unless-stopped
    environment:
      # Configurações do Banco
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: acamp_user
      PG_PASSWORD: ${DB_PASSWORD:-acamp_password_2025}
      PG_DATABASE: acamp_termo
      
      # Configurações da Aplicação
      NODE_ENV: production
      PORT: 3001
      
      # Timezone
      TZ: America/Campo_Grande
    ports:
      - "3001:3001"
    volumes:
      # Volume para PDFs assinados (persistente)
      - pdfs_assinados:/app/server/public/assinados
      # Volume para logs (opcional)
      - app_logs:/app/server/logs
    networks:
      - acamp-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ==========================================
  # Nginx Reverse Proxy (Opcional)
  # ==========================================
  nginx:
    image: nginx:alpine
    container_name: acamp-termo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - acamp-network
    depends_on:
      - app
    profiles:
      - with-nginx

# ==========================================
# Volumes Persistentes
# ==========================================
volumes:
  postgres_data:
    driver: local
    name: acamp-termo-postgres-data
  
  pdfs_assinados:
    driver: local
    name: acamp-termo-pdfs
  
  app_logs:
    driver: local
    name: acamp-termo-logs

# ==========================================
# Rede Interna
# ==========================================
networks:
  acamp-network:
    driver: bridge
    name: acamp-termo-network

